Repository hmueller01/pubsubclient3, pull requests merged in 2025-07, with the labels that each got.

#48 Add check for nullptr in CHECK_STRING_LENGTH
  src/PubSubClient.h
Labels: bug

#50 move CHECK_STRING_LENGTH to PubSubClient.cpp
  src/PubSubClient.cpp
  src/PubSubClient.h
Labels: enhancement

#54 implemented writeNextMsgId()
  src/PubSubClient.cpp
  src/PubSubClient.h
  tests/src/subscribe_spec.cpp
Labels: bug, enhancement

#49 support publish at QoS 1 and 2
  README.md
  examples/mqtt_auth/mqtt_auth.ino
  examples/mqtt_basic/mqtt_basic.ino
  examples/mqtt_esp8266/mqtt_esp8266.ino
  examples/mqtt_large_message/mqtt_large_message.ino
  examples/mqtt_publish_in_callback/mqtt_publish_in_callback.ino
  examples/mqtt_reconnect_nonblocking/mqtt_reconnect_nonblocking.ino
  examples/mqtt_stream/mqtt_stream.ino
  src/PubSubClient.cpp
  src/PubSubClient.h
  tests/src/connect_spec.cpp
  tests/src/keepalive_spec.cpp
  tests/src/publish_spec.cpp
  tests/src/receive_spec.cpp
  tests/src/subscribe_spec.cpp
Labels: enhancement
